Name: App.api
Host: 0.0.0.0
Port: 8080
Timeout: 2000

Auth:
  AccessSecret: BVRUXrPJeX7fGnLJVTTbt9wfDhn
  AccessExpire: 86400

CROSConf:
  Address: '*'

Log:
  ServiceName: AppApiLogger
  Mode: file
  Path: /home/data/logs/App/api
  Level: info
  Compress: false
  KeepDays: 7
  StackCoolDownMillis: 100


RedisConf:
  Host: 127.0.0.1:6379

CasbinDatabaseConf:
  Type: mysql
  Host: 127.0.0.1
  Port: 3306
  DBName: simple_admin
  Username: # set your username
  Password: # set your password
  MaxOpenConn: 100
  SSLMode: disable
  CacheTime: 5

CasbinConf:
  ModelText: |
    [request_definition]
    r = sub, obj, act
    [policy_definition]
    p = sub, obj, act
    [role_definition]
    g = _, _
    [policy_effect]
    e = some(where (p.eft == allow))
    [matchers]
    m = r.sub == p.sub && keyMatch2(r.obj,p.obj) && r.act == p.act
